name: Prettier Check

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Prettier Check
        run: npx prettier --check .
